### ISSUE TITLE
[Feature Request] A Dockerfile

### ISSUE THREAD

**Issue by ghost** [dotnize/chessu#5]
Hey mate, pretty much searched the entire github site for a way to selfhost a very simple online Chess / chess-versus game for my students. I ended up here on your beautiful project 👍 

The school where I work has a fairly strict network setup, even for teachers, so self-hosting is sometimes easier to get around, or simply avoid, the restrictions. Most '.ru' and '.su' domains are simply not permitted without the use of a VPN or similar tools.

It would be hella awesome, if there was a Dockerfile made for this project, as it seems damn near perfect for my use-case.

I would gladly donate some money, if that could be an encouragement?

Much love,
VP-EN

**Comment by dotnize** [comment]
I appreciate your interest in this project! Unfortunately, I can't work on this right now since I'm very busy and I'm still not that familiar with Docker.

I currently have other priorities for this project (#4), but I'll be sure to consider this in the future since Docker is a tool I'm interested in.

This project is open-source though, so feel free to make a fork and implement this yourself or hire other developers to do it :)

**Comment by ghost** [comment]
Thanks for the reply!

I'll also try and do some research on it, not too experienced in creating dockerfiles. If I'm successful, I'll create a PR.

**Comment by hriprsd** [comment]
@dotnize I can work on the Dockerfile bit if there's still scope. please lemme know, i would love to do it this Hacktoberfest :)

**Comment by dotnize** [comment]
@hriprsd sure, feel free to give it a shot!

**Comment by hriprsd** [comment]
#29 solves this - hopefully 😉
